### ISSUE TITLE
Flera kurskoder på samma tenta

### ISSUE THREAD

**Issue by guskal01** [dtekcth/plugg#15]
![image](https://user-images.githubusercontent.com/30019468/112170506-643d8800-8bf3-11eb-8850-3a34be65192a.png)

Att det ser ut såhär är inte helt ovanligt. Vad är bästa lösningen? Att bara lägga tentan i en av mapparna eller att lägga en kopia i varje? Eller kanske typ en symlink i varje mapp?

**Comment by toasterbag** [comment]
Den borde defenitivt ligga i alla mapparna. Med tanke på att tentorna inte är så stora lutar jag åt att bara ha flera kopior istället för att strula runt med symlänkar. @Hugsim får gärna väga in.

**Comment by Hugsim** [comment]
Jag skulle nog hålla med @toasterbag, kopiera tentan till alla olika Chalmers-kurskoder

**Comment by guskal01** [comment]
Ok, jag gör så!
